### ISSUE TITLE
lab3_2/Task3.py

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/Istomin-Arseniy#5]
Пропишите, пожалуйста дефолтные параметры, я с нескольких попыток не угадал, что именно надо скормить программе, чтобы она заработала, это можно сделать, например, как  здесь https://stackoverflow.com/questions/22402548/default-values-on-empty-user-input . Ну или просто напишите мне в ответ на issue , что нужно ей дать.

btw, количество частиц это скорее number, а не amount.

**Comment by IstominArseniy** [comment]
Добавил значения по умолчанию
