### ISSUE TITLE
lab3_2 review

### ISSUE THREAD

**Issue by AndreevP** [python-practice-b02-927/Istomin-Arseniy#6]
У вас отличная работа, прослеживается развитие проекта, структура кода. Анимация работает корректно. Но есть большой минус -- вы не пишите комментарии и док-стринги, в этот раз ставлю вам полный балл, так как вы все равно проделали хорошую работу, но впредь не игнорируйте это требование. Так же все такие есть небольшие проблемы с pep8 (сокращайте длины строк в соответствии с правилами).

**Comment by IstominArseniy** [comment]
Хорошо
